backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "blog"
    label: "Blogbeiträge"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - label: "Kategorie"
        name: "category"
        widget: "select"
        options: ["Transite", "Grundlagen", "Impulse", "Sternzeichen", "Mondphasen", "Allgemein"]
        default: "Allgemein"
      - {label: "Als Top-Thema im Banner anzeigen?", name: "highlight", widget: "boolean", default: false, required: false}
      - {label: "Kurzbeschreibung (für den Banner)", name: "description", widget: "text", required: false}
      - {label: "Badge Text (z.B. 'Aktiv im 6. Haus')", name: "badge", widget: "string", required: false}
      - {label: "Beitragsbild auswählen", name: "image", widget: "image", choose_url: true, required: false}
      - {label: "Inhalt", name: "body", widget: "markdown"}
